/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;

public class App {
    public String getGreeting()
    {
        System.out.println("Sreeni test1");
        return "Hello world.";
    }

    public  String  getWeather(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        ArrayList<Integer> allTemperatures = new ArrayList<>();
        for (int[] weekList : weeklyMonthTemperatures){
            for (int s : weekList){
                //System.out.println("Array List values: "+s);
                allTemperatures.add(s);

            }
        }

        Collections.sort(allTemperatures);
        int minTemperature = Collections.min(allTemperatures);
        int maxTemperature = Collections.max(allTemperatures);

        System.out.println("Low: " + minTemperature);
        System.out.println("High: " + maxTemperature);
        Collections.min(allTemperatures);

        HashSet<Integer> hs = new HashSet<>();

        for (int temps: allTemperatures){
            //System.out.println("temps"+temps);
            hs.add(temps);
        }

        for(int i=minTemperature; i<maxTemperature; i++){
            if (!hs.contains(i)){
                System.out.println("Never saw temperature: "+i);
            }

        }

        int concatString = minTemperature+maxTemperature;

        return "51";


    }

    public String tally(ArrayList<String> vot){

        HashMap<String,Integer> hm = new HashMap<>();


        for(String name: vot){
            //System.out.println("printing : "+name);

            int count = hm.containsKey(name) ? hm.get(name) : 0;
            hm.put(name, count + 1);

        }

        //System.out.println("max value"+ Collections.max(hm));

        System.out.println("hashmap print: "+hm);

        //iterate hashmap to get the max votes name
        //ArrayList<int> voteCount = new ArrayList<int>();
        String winnerName = "";
        int winCount = 0;
        for(String val: hm.keySet()){
            System.out.println("Printing the value: "+ hm.get(val));
            if(winCount < hm.get(val)){
                winCount = hm.get(val);


            }

        }

                if (hm.containsValue(winCount)){
                    System.out.println("value found ");
                };
        System.out.println("winCount"+winCount);
        return "Hello";
    }

    public String election(){
        ArrayList <String> votes = new ArrayList();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = tally(votes);
        System.out.println(winner + " received the most votes!");
        return "will return later";
    }

   public static void main(String[] args)
    {
        System.out.println("Sreeni Test message");
       System.out.println(new App().getGreeting());


    }
}
