/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Array;
import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.Scanner;
import com.google.gson.Gson;

public class App {

    public static void main(String[] args) throws FileNotFoundException {

        //Scanner reader = new Scanner(new File("src/main/resources/recentquotes.json"));

        Gson gson = new Gson();
        Quote[] newQuotes = gson.fromJson(new FileReader("src/main/resources/recentquotes.json"), Quote[].class);

        System.out.println("newQuotes length = " + newQuotes.length);
        int randomNum = (int) (Math.random() * newQuotes.length);
        System.out.println("randomNum: "+randomNum);
        System.out.println("newQuote = " + newQuotes[randomNum]);
        System.out.println("newQuote = " + newQuotes[randomNum].getQuote());


    }
}
